import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:login/ui/screens/event/event.dart';
import 'package:login/ui/screens/scrap/scrap.dart';
import 'package:login/ui/screens/policy/policy_list.dart';
import 'package:login/ui/screens/user/my_page.dart';
import 'package:shimmer/shimmer.dart';
import 'package:login/domain/blocs/blocs.dart';
import 'package:login/data/env/env.dart';
import 'package:login/ui/helpers/helpers.dart';
import 'package:login/ui/screens/home/home_page.dart';
// import 'package:login/ui/screens/notifications/notifications_page.dart';
// import 'package:login/ui/screens/profile/profile_page.dart';
// import 'package:login/ui/screens/reels/reel_home_screen.dart';
// import 'package:login/ui/screens/searchs/search_page.dart';
import 'package:login/ui/themes/theme_colors.dart';

part 'text_custom.dart';
part 'fieldNaru.dart';
part 'btnNaru.dart';
part 'bottom_nav.dart';
part 'shimmerNaru.dart';
part 'item_modal.dart';
part 'CorrectWordParameter.dart';
